### ISSUE TITLE
Cannot locate GPIB library in PyVisa implementation

### ISSUE THREAD

**Issue by WeAreGeth** [tivek/gpib_ctypes#2]
Hello tivek,

Thank you for creating a gpib backend that I can use in PyVisa with PyVisa-py. The issue I am having relates to an inability to load the GPIB library. As given in your example, there is a function that can be called to have PyVisa recognize gpib_ctypes as the default GPIB module, but it seems not to be working for me. 

My code:

`from gpib_ctypes import make_default_gpib`
`make_default_gpib()`

`import visa as vi`

`connections=vi.ResourceManager('@py')`
`print(connections.list_resources())`             #Error here

Error log:

- /home/we-are-geth/.local/lib/python3.6/site-packages/gpib_ctypes/gpib/gpib.py:54: UserWarning: GPIB library not found. Please manually load it using _load_lib(filename). All GPIB functions will raise OSError until the library is manually loaded.
  warnings.warn(message)
Traceback (most recent call last):
  File "/home/we-are-geth/Documents/PyVisa_Testing/Hello_World.py", line 7, in <module>
    print(connections.list_resources())
  File "/home/we-are-geth/.local/lib/python3.6/site-packages/pyvisa/highlevel.py", line 1637, in list_resources
    return self.visalib.list_resources(self.session, query)
  File "/home/we-are-geth/.local/lib/python3.6/site-packages/pyvisa-py/highlevel.py", line 326, in list_resources
    for key, st in sessions.Session.iter_valid_session_classes()], [])
  File "/home/we-are-geth/.local/lib/python3.6/site-packages/pyvisa-py/highlevel.py", line 326, in <listcomp>
    for key, st in sessions.Session.iter_valid_session_classes()], [])
  File "/home/we-are-geth/.local/lib/python3.6/site-packages/pyvisa-py/gpib.py", line 56, in list_resources
    return ['GPIB0::%d::INSTR' % pad for pad in _find_listeners()]
  File "/home/we-are-geth/.local/lib/python3.6/site-packages/pyvisa-py/gpib.py", line 56, in <listcomp>
    return ['GPIB0::%d::INSTR' % pad for pad in _find_listeners()]
  File "/home/we-are-geth/.local/lib/python3.6/site-packages/pyvisa-py/gpib.py", line 34, in _find_listeners
    if gpib.listener(BOARD, i) and gpib.ask(BOARD, 1) != i:
  File "/home/we-are-geth/.local/lib/python3.6/site-packages/gpib_ctypes/gpib/gpib.py", line 417, in listener
    sta = _lib.ibln(board, pad, sad, ctypes.byref(present))
  File "/home/we-are-geth/.local/lib/python3.6/site-packages/gpib_ctypes/gpib/gpib.py", line 59, in f
    raise OSError(message)
OSError: GPIB library not found. Please manually load it using _load_lib(filename). All GPIB functions will raise OSError until the library is manually loaded.
[Finished in 0.3s with exit code 1]

Thank you for any assistance!

**Comment by tonyzzz321** [comment]
Do you have NI GPIB driver installed? Does the file 'gpib-32.dll' or 'ni4882.dll' exist in the system32 folder? Is your python 32-bit or 64-bit?

**Comment by apiece82** [comment]
Hi Tivek,

I also got an error with above code:

  File "C:\ProgramData\Anaconda3\lib\site-packages\pyvisa-py\sessions.py", line 170, in __init__
    raise ValueError(msg)

ValueError: Please install linux-gpib to use this resource type.
No module named 'gpib'

gpib-32.dll exist in C:\windows\system32\  and using python 32bit

**Comment by tonyzzz321** [comment]
Hi apiece82,

What the function make_default_gpib() is doing is to make the module name 'gpib' point to gpib_ctypes's 'gpib' module instead of the default one. The default 'gpib' module is pointing to linux-gpib's 'gpib' module if you are on Linux and have linux-gpib installed. Or it does not exist if you are on Windows or if you don't have linux-gpib installed on Linux.

I think in your case the module name 'gpib' does not exist, that means you are on Windows or on Linux but linux-gpib not installed. The default 'gpib' module name is not correctly overwritten and not pointing to gpib_ctypes's 'gpib' module. This is not the same error WeAreGeth is experiencing. For debugging purpose, can you try the "Object-oriented GPIB API" from https://gpib-ctypes.readthedocs.io/en/latest/usage.html and see if you can manually talk to the instrument without using py-visa?

**Comment by apiece82** [comment]
Hi tonyzzz321 ,

Yes, the "Object-oriented GPIB API" in the link provided is working good.

You mentioned: "The default 'gpib' module name is not correctly overwritten and not pointing to gpib_ctypes's 'gpib' module." 

How to overwrite the default 'gpib' module name, and ensure it pointing to gpib_ctypes?

**Comment by tonyzzz321** [comment]
from gpib_ctypes import make_default_gpib
make_default_gpib()

Executing the above two lines before importing visa library from pyvisa should do the trick. Would you mind sharing your source code?
